### ISSUE TITLE
Performance issues with using Ladybug Core libraries in GH

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#10] opened 2016-04-27 03:15 UTC
I have two key questions that, with answers, I believe I can really start cleaning/building out the revised version of Ladybug for GH.  I uploaded a GH test file that is trying to use the new libraries for ladybug here:
https://github.com/ladybug-analysis-tools/ladybug/blob/master/tests/comfortModelTest.gh?raw=true
I am just importing the core right now but I know that we will eventually import ladybugx once we convert the ladybug-Dynamo repo over to a generic ladybug geometry repo.

My two questions about this file are:
1) Why is it taking >15 seconds to import an EPW file?  The original import EPW component typically ran in less than a second for me.  If the reason is that we should have a faster method ont he EPW class for importing all of the EPW data at once, I would be happy to write it.

2) Why is my test code for the PMV class working in the test.py file in Atom but not in the GH file?

I'll keep plugging away at these uestions myself but, if anyone has any insight in the meantime, I would greatly appreciate it.

-Chris

**Comment by mostaphaRoudsari** [comment] 2016-04-27 03:39
@chriswmackey short answer to question 1 is that the current import epw is doing much more than the old version and it is normal that it will take longer. Still 15 seconds is too much. I will have a look later this week and will have better answers for both of your questions.

**Comment by chriswmackey** [comment] 2016-04-27 12:22
@ mostaphaRoudsari ,

Thanks for the response and the plan sounds good. There's no rush on the answers but I just wanted to post the question up here so that it did not fall through the cracks. I might just be using the EPW class incorrectly and that could be the reason why it is taking 15 seconds.

-Chris

**Comment by mostaphaRoudsari** [comment] 2016-05-11 22:27
@chriswmackey we have already addressed your question number 2. Back to 1 I started running some test and I found some interesting results. If I run the same code in AtomEditor it will take between 2-3 seconds.

The same code in Grasshopper takes around 28 seconds on my machine but if I don't assign them to component outputs it will take 3.6 seconds (close to atom editor). Most of the time is the time that it takes for GHPython component to register the values to outputs.

I assume that Grasshopper python component does some type checking when it registers the values to outputs and that's what makes the process slow as our outputs are not an standard time. To test the idea I cast the values from LBData to string and then assign them to output. Interestingly enough it takes only 5 seconds even with the extra time for type casting.

Here is the 3 options next to each other:
![image](https://cloud.githubusercontent.com/assets/2915573/15198324/b536fcfa-17a4-11e6-91be-e68173db3b56.png)

I'm curios to hear @piac's thoughts on this. Does GHPython do type-casting for the outputs and is there a way to turn off type-casting for the output?

You can download the file from [this link](https://github.com/ladybug-analysis-tools/ladybug/raw/master/tests/importEPW_performance_test.gh) to test in on your machine.

**Comment by piac** [comment] 2016-05-12 08:58
Hi @mostaphaRoudsari

I'm sorry I'm swamped in a ton of other things right now. I promise I will look into this, though, if you could do me a favor first. Could you time the same thing after gathering all results in a python list? (and not assigning it as output?)

that is, rather than...
output = get_your_outputdata()
do this:
temp_list = list(get_your_outputdata())

the temp_list needs not be set to an output variable. I would like to rule out first that the problem is not some sort of lazy evaluation. Then please let me know

**Comment by mostaphaRoudsari** [comment] 2016-05-12 12:10
Hi @piac, Thank you for the quick reply even though I know you're very busy. I did what you suggested and it takes less than 4 second. Just in case I'm copying the code here. Let me know if I need to do anything else.

```python
import sys
import time
from scriptcontext import sticky

if "lb_lib_path" in sticky:
    sys.path.append(sticky["lb_lib_path"])

try:
    from ladybug.epw import EPW
    from ladybug.wrapper import Wrapper
except ImportError:
    raise ImportError("Failed to import Ladybug libraries.\n" + \
                      "Set-up path to Ladybug libraries in ladybug_ladybug component")

if _epwFile:
    st = time.time()
    epwData = EPW(_epwFile)
    epwData.location
    tmp1 = list(epwData.dryBulbTemperature.values(header=True))
    tmp2 = list(epwData.dewPointTemperature.values(header=True))
    tmp3 = list(epwData.relativeHumidity.values(header=True))
    tmp4 = list(epwData.windDirection.values(header=True))
    tmp5 = list(epwData.windSpeed.values(header=True))
    tmp6 = list(epwData.directNormalRadiation.values(header=True))
    tmp7 = list(epwData.diffuseHorizontalRadiation.values(header=True))
    tmp8 = list(epwData.globalHorizontalRadiation.values(header=True))
    tmp9 = list(epwData.directNormalIlluminance.values(header=True))
    tmp10 = list(epwData.diffuseHorizontalIlluminance.values(header=True))
    tmp11 = list(epwData.globalHorizontalIlluminance.values(header=True))
    tmp12 = list(epwData.totalSkyCover.values(header=True))
    tmp13 = list(epwData.liquidPrecipitationDepth.values(header=True))
    tmp14 = list(epwData.atmosphericStationPressure.values(header=True))
    tmp15 = list(epwData.years.values(header=True))
    print time.time() - st
```

**Comment by mostaphaRoudsari** [comment] 2016-05-12 12:16
Also updated the [file](https://github.com/ladybug-analysis-tools/ladybug/raw/master/tests/importEPW_performance_test.gh).
![image](https://cloud.githubusercontent.com/assets/2915573/15214162/7e93273a-1819-11e6-9afe-32bc51a270e8.png)

**Comment by piac** [comment] 2016-05-12 15:22
@mostaphaRoudsari Is it any faster if you assign the output after constructing an explicit list() ?

**Comment by mostaphaRoudsari** [comment] 2016-05-12 15:58
@piac no it doesn't. It actually adds to the time (~35 seconds).

Back to the error, you need to change the filepath to a valid epw file. You can download one from [epwmap](http://mostapharoudsari.github.io/epwmap/). Download the zip file and extract it. There should be an *.epw file that you can use.

**Comment by piac** [comment] 2016-05-12 17:35
Ah OK — I understand now. Welcome to the _Magic World Of Goo_&trade;. :)

This is no GhPython bug or limitation. It's just Grasshopper having to do lots of very hard work to find the best match for your custom types, and failing miserably every single time after having done the hard work. You have an easy time with types because you are using Python, but Grasshopper needs to know how to bake (if possible), preview, etc, every object. That's why IGH_Goo was invented. To give a specific "ubertype" to all types.
Because your types (I think, I did not investigate very much) are all custom, you will save GH lots of effort if you give it the right Goo already.

As far as I know, IGH_Goo will be removed from Grasshopper 2.0 because it creates some anomalies and people have a hard time with it, but it's also useful right now. Here is how you fix your problem. If you use numbers, geometry, etc, there are also special Goos to use. They are all in the same Grasshopper.Kernel.Types namespace.

[importEPW_performance_test_goo.zip](https://github.com/ladybug-analysis-tools/ladybug/files/261930/importEPW_performance_test_goo.zip)

**Comment by mostaphaRoudsari** [comment] 2016-05-13 00:16
@piac thank you for the clarification and the example file.

It solves the issue with the running time but the results is very similar to casting them to string. Is there a way to unwrap the GH_ObjectWrapper and take my original objects back?

The whole point of creating custom objects vs numbers and strings is to make the workflow more efficient. We have a full list of methods that now won't really be useful. By casting them to goo we're back to the step one an basically we have to go through all we have been through for the current development. :|

Is there any alternative solution to this? Is there a way to assign *No Type Hint* to outputs similar to what I can do for the inputs? The other solution that I can thing about is to output every list as a single object and then let the user unwrap them using a different component to get the values. I'm not sure if people will like it, and it's definitely not a great design, but that looks like the solution to address both the performance and use custom types.

Thanks again for your great support. Let me know if you think that I should post this to Grasshopper forum instead of here so at least more people can see your replies as a reference.

**Comment by piac** [comment] 2016-05-13 10:26
Well, this is how the Grasshopper SDK works.

In general, it seems to me that there is some work to do on OOP design, because 'dewPointTemperature' (for example) has tons of class instances, but they actually would belong to a single class, not to tons of spread around classes. If you use fewer classes, of course there will be no problem passing it around. Generally speaking, also, a single 'output' parameter in GH does not usually return text and numbers mixed together.

Secondarily, many little custom objects will take time to convert to IGH_Goo. What you could do, is reduce the amount of little objects by placing them in larger "container" objects, provided that those are not lists or implement IEnumerable. This way, only a single large object will be passed. Or even just pass the '_epwFile' around and just its data. Also every single number is actually not a 'number' (you might have your own reasons that I did not have time to investigate).

Lastly, but actually your first question: "Is there a way to unwrap the GH_ObjectWrapper and take my original objects back?" Yes, the Grasshopper SDK reasons everything in terms of IGH_Goo but GHPython calls .ScriptVariable() on these Goo's, and therefore will give you your object back. Use the type() function to follow what is going on. Basically, you will save time by creating GH_ObjectWrapper, but you will not see them again.

**Comment by mostaphaRoudsari** [comment] 2016-05-13 13:06
Thanks @piac!

Ladybug data currently does not inherent from ```object```. The image below shows why. I wanted ```__repr__``` to be human readable. That's why you see them as instances and not a single class. I ended up writing my own [Wrapper class](https://github.com/ladybug-analysis-tools/honeybeex/blob/master/honeybeex/wrapper.py) to address this issue. I will update Ladybug classes soon.

![image](https://cloud.githubusercontent.com/assets/2915573/15248532/b78c16f8-18e8-11e6-96b3-30b9573dce0f.png)

Ladybug works as you mentioned in the first two paragraphs. For instance ```epwData.dryBulbTemperature``` is a ```LBDataList``` which is a "container". I used ```LBDataList.values(header=True)``` method to get the values as a single list with a header before assigning them to outputs because I think it's a much better interface to see the values and not a single object from each output. Putting them in a container or passing them around as epwfile object can work too but as I previously mentioned is not my favorite design choice.

The reason that the outputs are instances of ```LBData``` and not ```string``` or ```int``` is because they are carrying other necessary information such as unit, datetime, etc. 

Lastly it was my mistake. I was passing the objects through a panel before checking the ```type```. It now works as expected and I can get the original object. I think we will use your suggestion to use ```GH_ObjectWrapper```. Thanks again. It was very helpful. :)

Looking forward to test GH2 soon.

**Comment by piac** [comment] 2016-05-13 13:46
If you override the .Net ToString(), you can get a similar result inheriting from object.
You could also inherit from IGH_Goo or one of its derived types, so you would not need to construct an empty object. [This is](https://github.com/piac/TurtleMesh/blob/master/TurtleGh/GH_TurtleMesh.cs) for example what Turtle does.

**Comment by mostaphaRoudsari** [comment] 2016-05-14 12:31
Thank you for the tip. ```ToString()``` will be very useful. I can remove Wrapper class from Ladybug.

**Comment by chriswmackey** [comment] 2016-05-15 04:45
@mostaphaRoudsari  and @piac ,
I just wanted to thank you for all of your attention to this over the last few days. I learned a lot from your conversation and I am very much looking forward to seeing an implementation with ToString() and GH_ObjectWrapper.  And, of course, I am absolutely looking forward to GH2!

**Closed** 2017-07-28 18:56 UTC
Labels: enhancement, help wanted, new development
